📦️ package: add Sentry

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -14,7 +14,15 @@ pnpm lint:eslint || {
   echo " "
   echo -e "${RED} *pouts* Look what you did! Your code is full of lint errors... I-it's not like I stayed up all night worrying about your code style or anything...${NC}"
   echo " "
-  exit 1
+  pnpm eslint . --fix || {
+    echo " "
+    echo -e "${RED} T-this is impossible! Your code is way too messy for me to fix! Clean it yourself! *storms off angrily*${NC}"
+    echo " "
+    exit 1
+  }
+
+  echo " "
+  echo -e "${GREEN} Hmph... I fixed your code... but don't think this means I *like* helping you or anything!${NC}"
   echo " "
 }
 
@@ -26,14 +34,21 @@ echo -e "${CYAN} *sigh* Your code needs prettifying again... You really can't do
 
 pnpm lint:prettier || {
   echo " "
-  echo -e "${RED} W-what did you do to your code?! It's so messy I can't even format it... Not that I care, but you should be more careful!${NC}"
+  echo -e "${MAGENTA} W-what is this mess?! I can't believe you let it get this bad... F-fine, I'll clean it up for you... but it's not because I *want* to or anything! >///<${NC}"
   echo " "
-  exit 1
+  pnpm prettier --write --list-different . || {
+    echo " "
+    echo -e "${RED} Ugh! This code is way too messy for me to clean! Y-you better clean it yourself! *storms off*${NC}"
+    echo " "
+    exit 1
+  }
+  echo " "
+  echo -e "${GREEN} H-here! I cleaned it up... You really can't do anything by yourself, can you?${NC}"
   echo " "
 }
 
 echo " "
-echo -e "${GREEN} *fidgets* Now it's pretty... thanks to me, obviously! You better appreciate my hard work!${NC}"
+echo -e "${GREEN} *fidgets* Now it's pretty... thanks to me, obviously! ${NC}"
 
 echo " "
 echo -e "${YELLOW} Time for tests... you probably broke something again... n-not that I'm expecting it or anything...${NC}"
